Andrey_marchuk_18.01.2023
NET-18/Homework pull request #103
Opened 2023-01-18 15:37 UTC by AndrewM4k

2023-01-24 08:52 UTC, ivan-tms requested changes
Поправь трохи и будет топ

2023-01-24 08:52 UTC, ivan-tms commented on ConsoleApp3/Program.cs
> +            list.Add(new SqlParameter("@a8", "A8"));
Лучше сделать имя параметра одинаковым для всех, не придётся совать костыль внутрь строки запроса

2023-01-24 08:52 UTC, ivan-tms commented on ConsoleApp3/Program.cs
> +            var adapter = new SqlDataAdapter("SELECT * FROM  [Models]", conn);
Нужен using

2023-02-04 11:55 UTC, AndrewM4k commented on ConsoleApp3/Program.cs
> +            list.Add(new SqlParameter("@a8", "A8"));
fixed

2023-02-04 11:55 UTC, AndrewM4k commented on ConsoleApp3/Program.cs
> +            var adapter = new SqlDataAdapter("SELECT * FROM  [Models]", conn);
fixed

2023-02-10 23:13 UTC, closed without merging