Andrey.marchuk_25.01.2023
NET-18/Homework pull request #106
Opened 2023-01-24 19:55 UTC by AndrewM4k

2023-01-24 19:58 UTC, ivan-tms requested changes

2023-01-24 19:58 UTC, ivan-tms commented on Homewok_25.01.2023/Program.cs
> +            Console.WriteLine("All");
Поленился менюшку сделать значит...
Тогда значит доебусь и за пустые строки не там где надо

2023-01-24 19:58 UTC, ivan-tms commented on Homewok_25.01.2023/DatabaseContext.cs
> +
Убери

2023-01-24 19:58 UTC, ivan-tms commented on Homewok_25.01.2023/DatabaseContext.cs
> +        public DbSet<WeatherForecast> WeatherForecasts { get; set; }
После него поставь пустую строку

2023-01-28 10:25 UTC, ivan-tms requested changes

2023-01-28 10:25 UTC, ivan-tms commented on Homewok_25.01.2023/Program.cs
> +
Убери =)

2023-02-04 11:51 UTC, AndrewM4k commented on Homewok_25.01.2023/Program.cs
> +            Console.WriteLine("All");
я lazy piece of shit(

2023-02-04 11:51 UTC, AndrewM4k commented on Homewok_25.01.2023/DatabaseContext.cs
> +
fixed

2023-02-04 11:51 UTC, AndrewM4k commented on Homewok_25.01.2023/DatabaseContext.cs
> +        public DbSet<WeatherForecast> WeatherForecasts { get; set; }
fixed

2023-02-04 11:52 UTC, AndrewM4k commented on Homewok_25.01.2023/Program.cs
> +
fixed

2023-02-07 22:07 UTC, closed without merging