Knyazeva 26.10.2022
NET-18/Homework pull request #15
Opened 2022-10-25 19:29 UTC by LyubovKnyazeva

2022-10-25 19:57 UTC, ivan-tms requested changes

2022-10-25 19:57 UTC, ivan-tms commented on HomeWork2/HomeWork2/Program.cs
> +    public class Person
добавь ещё конструктор без параметров

2022-10-25 19:57 UTC, ivan-tms commented on HomeWork2/HomeWork2/Program.cs
> +        public Program(double x, double y, double z)
удали этот конструктор, у класса `Program` его не должно быть

2022-10-25 19:57 UTC, ivan-tms commented on HomeWork2/HomeWork2/Program.cs
> +        public static double Distance(Program a, Program b)
этот метод должен принимать две точки, а не два `Program`'а)

2022-10-25 19:57 UTC, ivan-tms commented on HomeWork2/HomeWork2/Program.cs
> +            return Math.Sqrt(dX * dX + dY * dY + dZ * dZ);
желательно использовать `Math.Pow`, но и так нормально

2022-10-25 19:57 UTC, ivan-tms commented on HomeWork2/HomeWork2/Program.cs
> +        public override string ToString() => $"{{X={x}, Y={y}, Z={z}}}";
похвально, что ты это знаешь, но перенеси это в структуру `Point` у класса `Program` не должно быть таких методов)
ещё можешь добавить подобный метод в `Person` и в методе `Print` просто выводить `person`, а не форматировать строку для вывода

2022-10-26 13:20 UTC, LyubovKnyazeva commented on HomeWork2/HomeWork2/Program.cs
> +    public class Person
пофикшено

2022-10-26 13:20 UTC, LyubovKnyazeva commented on HomeWork2/HomeWork2/Program.cs
> +        public static double Distance(Program a, Program b)
пофикшено

2022-10-26 13:20 UTC, LyubovKnyazeva commented on HomeWork2/HomeWork2/Program.cs
> +        public override string ToString() => $"{{X={x}, Y={y}, Z={z}}}";
пофикшено

2022-10-26 13:20 UTC, LyubovKnyazeva commented on HomeWork2/HomeWork2/Program.cs
> +        public Program(double x, double y, double z)
пофикшено

2022-10-26 13:20 UTC, LyubovKnyazeva commented on HomeWork2/HomeWork2/Program.cs
> +            return Math.Sqrt(dX * dX + dY * dY + dZ * dZ);
пофикшено

2022-10-26 16:01 UTC, ivan-tms requested changes

2022-10-26 16:01 UTC, ivan-tms commented on HomeWork2/HomeWork2/Program.cs
> +    public class Person
добавь в конструктор без параметров инициализацию дефолтными значениями (age = 15, name = "Someone" и т.п.)

2022-10-26 16:06 UTC, LyubovKnyazeva commented on HomeWork2/HomeWork2/Program.cs
> +    public class Person
Done

2022-10-29 05:46 UTC, closed without merging