homework_1_2
NET-18/Homework pull request #2
Opened 2022-10-24 23:20 UTC by Siion42

Домашка с прошлого занятия

2022-10-25 07:24 UTC, ivan-tms commented
если это домашка на прошлое занятие, то переименую PR и поставь дату занятия на которое оно было (вчерашнее - 24.10.2022)

2022-10-25 17:51 UTC, ivan-tms requested changes

2022-10-25 17:51 UTC, ivan-tms commented on arseni-ustinovich_26.10.2022/HW_4/Program.cs
> +        static double distance(XYZ a, XYZ b) => Math.Sqrt(Math.Pow(a._x - b._x, 2) + Math.Pow(a._y - b._y, 2) + Math.Pow(a._z - b._z, 2));
Методы должны называться с большой буквы

2022-10-25 17:51 UTC, ivan-tms commented on arseni-ustinovich_26.10.2022/HW_3/Program.cs
> +        static void MyOutput(Person A)
параметры методов должны именоваться в нижнем регистре

2022-10-25 17:51 UTC, ivan-tms commented on arseni-ustinovich_26.10.2022/HW_3/Program.cs
> +        public Person(int age, string name, string surname)
`this` здесь не обязательно, оно нужно было бы, если поля назывались также как и параметры метода

2022-10-26 21:41 UTC, Siion42 commented
Исправил!

2022-10-29 06:22 UTC, closed without merging