Andrew marchuk 26.10.2022
NET-18/Homework pull request #22
Opened 2022-10-26 11:30 UTC by AndrewM4k

2022-10-29 06:36 UTC, ivan-tms requested changes
исправь эти два коммента и будет норм

2022-10-29 06:36 UTC, ivan-tms commented on ConsoleApp5/Program.cs
> +    public static void Print()
в этот метод нужно передать `Person`'а для вывода

2022-10-29 06:36 UTC, ivan-tms commented on ConsoleApp4/Program.cs
> +    internal class Program
мне кажется это дз на 24, её здесь не должно быть)

2022-10-31 12:26 UTC, ivan-tms requested changes

2022-10-31 12:26 UTC, ivan-tms commented on ConsoleApp5/Program.cs
> +        public static void length(Koordinates a, Koordinates b)
Методы должны называться с большой буквы

2022-11-02 18:58 UTC, AndrewM4k commented on ConsoleApp4/Program.cs
> +    internal class Program
пофикшено

2022-11-02 18:58 UTC, AndrewM4k commented on ConsoleApp5/Program.cs
> +    public static void Print()
пофикшено

2022-11-02 19:09 UTC, AndrewM4k commented on ConsoleApp5/Program.cs
> +        public static void length(Koordinates a, Koordinates b)
пофикшено

2022-11-11 06:30 UTC, closed without merging