Sergey Yushkevich 31.10.2022
NET-18/Homework pull request #32
Opened 2022-10-27 23:02 UTC by Sergey-Yushkevich

2022-10-29 06:11 UTC, ivan-tms requested changes
в паре мест поменяй, остальное норм

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Employee.cs
> +                case < 150.0m:
можно сделать один иф на 150 и не париться =)
и в ошибке написать что-то типа "salary cannot be less than 150"

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Employee.cs
> +                throw new ArgumentException("You are slave. Sorry", nameof(this._experience));
неплохо, неплохо)))

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Person.cs
> +            if (!string.Equals(value?.ToLowerInvariant(), "male") && !string.Equals(value?.ToLowerInvariant(), "female"))
ещё в метод Equals, после сравниваемых string'ов, можно передать StringComparison.OrdinalIgnoreCase
это будет аналогичная строка как у тебя

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Person.cs
> +                throw new ArgumentException("It's not a gender stupid bitch!", nameof(this._gender));
ну чего ты так грубо со своими пользователями =)

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Person.cs
> +    public void Poop()
)))

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Person.cs
> +    public object Clone()
т.к. это специфичный метод именно для класса Person, то можно возвращать не object, а сразу Person, чтобы потом не кастить лишний раз

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Program.cs
> +            DismissStudent(alsoMe);
давно надо было это сделать)))

2022-10-29 06:11 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Student.cs
> +            throw new ArgumentException("You are alien. I am scared.", nameof(person.Age));
Шэлдон Купер скорее)

2022-10-29 14:57 UTC, Sergey-Yushkevich commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Person.cs
> +                throw new ArgumentException("It's not a gender stupid bitch!", nameof(this._gender));
Я толерантный, но все равно если человек умрет и спросят кто это был, ответят либо male либо female :)

2022-10-29 14:58 UTC, Sergey-Yushkevich commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Person.cs
> +    public object Clone()
а он ругается, так как я подключил интерфейс ICloneable, а там же только object возвращает

2022-10-29 14:59 UTC, Sergey-Yushkevich commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Program.cs
> +            DismissStudent(alsoMe);
ахахаххахахха грустно(((

2022-10-30 08:16 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022/Person.cs
> +    public object Clone()
не заметил что ты реализовал этот интерфейс
тогда да, работать не будет)

2022-10-30 08:17 UTC, closed without merging