added hw_5
NET-18/Homework pull request #33
Opened 2022-10-28 00:28 UTC by Siion42

Воть

2022-10-28 00:32 UTC, Siion42 commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +        }
Только я не понимать чего не работает след:
static void ExpelStudent(Student student)
{
        student = new Student();
}
если класс это ссылочный тип, то я просто меняю изменяю ссылку передаваемого аргумента, но она не менятеся. explain pls.

2022-10-29 06:14 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +        }
ты создаёшь новый объект в куче и ссылку на него записываешь в аргумент
после завершения метода аргумент `student` удалится, а новый объект `Student` потом будет очищен, т.к. ссылок на него больше нет

если бы ты написал что-то типа `student.Course = 3`, то объект, который ты туда передал изменился бы

2022-10-29 06:21 UTC, ivan-tms requested changes
добавь валидацию, в `Program` пару моментов исправь и будет норм

2022-10-29 06:21 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +        public int Age { get; set; }
не мешало бы конечно валидацию добавить, т.к. я могу передать туда -10 и это будет совсем некорректно
и валидация нужна не только для возраста

2022-10-29 06:21 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +            PersonInfo(student.Person);
классно придумано

2022-10-29 06:21 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +                Gender = "Horse",
валидация затем и нужна, чтобы у человека вдруг пол не стал "лошадь")))

2022-10-29 06:21 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +                Job = "Senior Fool",
неплохая вакансия, надо поискать))

2022-10-29 06:21 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +            int RisingSalary = 90;
переменные внутри метода должны именоваться с маленькой буквы

2022-10-29 06:21 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +            WageInc(myEmployee, 90);
передай сюда `risingSalary`
неплохой рейз кстати, тоже такой хочу)

2022-10-29 10:39 UTC, Siion42 commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +        }
ну логично-логично)

2022-10-29 10:41 UTC, Siion42 commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +            WageInc(myEmployee, 90);
мечтать не вредно=))

2022-10-29 10:43 UTC, Siion42 commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +                Gender = "Horse",
![1615410118171494695](https://user-images.githubusercontent.com/116181961/198827007-c5eb68e9-d0c3-46c5-9f9c-9e730b14c8d5.jpg)
сейчас такое время, поэтому валидация для гендера это сложно(

2022-10-29 11:21 UTC, Siion42 commented
Переменные изменил. Кое-где исправил валидацию. Кое-где добавил. Для стинговых значений а-ля имени не хочу делать валидацию, ибо это проверки на числа и левые знаки делать, а це скучно=(

2022-10-30 08:19 UTC, ivan-tms commented on arseni-ustinovich_31.10.2022/HW_5/Program.cs
> +                Gender = "Horse",
тогда ладно)

2022-11-07 07:11 UTC, Siion42 commented
я че-то запутался в гите пиздец...

2022-11-11 06:32 UTC, closed without merging