Knyazeva 31.10.2022
NET-18/Homework pull request #38
Opened 2022-10-30 15:35 UTC by LyubovKnyazeva

2022-10-30 16:30 UTC, ivan-tms requested changes

2022-10-30 16:30 UTC, ivan-tms commented on Homework3/Homework3/Program.cs
> +    public class Employee : Person
это хорошо, что ты знаешь про наследование, но я просил именно свойство с типом `Person`

2022-10-30 16:30 UTC, ivan-tms commented on Homework3/Homework3/Program.cs
> +        public int RaisePercent
если у тебя таки гетеры и сетеры, то используются автоматические свойства
с ними не придётся писать эти простыни гетеров и сетеров

2022-10-30 16:30 UTC, ivan-tms commented on Homework3/Homework3/Program.cs
> +    public class Student : Person
опять же, нужно было свойство

2022-10-30 16:30 UTC, ivan-tms commented on hm3
> +homework3
удали этот файл

2022-10-30 16:30 UTC, ivan-tms commented on HomeWork2/HomeWork2/Program.cs
> +﻿using System;
оставь только домашку на 31.10

2022-11-10 07:01 UTC, LyubovKnyazeva commented on Homework3/Homework3/Program.cs
> +    public class Employee : Person
Пофикшено)

2022-11-10 07:01 UTC, LyubovKnyazeva commented on Homework3/Homework3/Program.cs
> +        public int RaisePercent
Пофикшено)

2022-11-10 07:01 UTC, LyubovKnyazeva commented on Homework3/Homework3/Program.cs
> +    public class Student : Person
Пофикшено)

2022-11-10 07:01 UTC, LyubovKnyazeva commented on hm3
> +homework3
Пофикшено)

2022-11-10 07:01 UTC, LyubovKnyazeva commented on HomeWork2/HomeWork2/Program.cs
> +﻿using System;
Пофикшено)

2022-11-11 06:37 UTC, closed without merging