Bobko Alexander 31.10.2022
NET-18/Homework pull request #41
Opened 2022-10-30 17:54 UTC by lamer27

2022-10-30 21:11 UTC, ivan-tms requested changes

2022-10-30 21:11 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +        public Student(Person person, string University, int Course, string Faculty)
аргументы методов должны именоваться с маленькой буквы

2022-10-30 21:11 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +        public string GetCourse()
вместо этого метода и метода `SetCourse` сделай одно свойство `Course`
делай валидацию в сеттере

2022-10-30 21:11 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +
оставляй только одну пустую строку между классами\методами
между полями и свойствами не надо оставлять пустое пространство

2022-10-30 21:11 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +                    _gender = "Дед",
неплохо))

2022-10-30 21:11 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +
эту простыню тоже надо убрать)

2022-10-30 21:11 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +        public string GetAge()
вместо этого сделай свойство, как описал ниже

2022-10-30 21:11 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +        public string _name { get; set; }
лучше сделай это полями, и к ним добавь свойства для валидации значений

2022-10-31 10:24 UTC, lamer27 commented on Homework31.10/Homework31.10/Program.cs
> +        public string GetCourse()
Так Course у нас инт, а GetCourse строка, придёться создавать дополнительную переменную для стринга, есть ли смысл?

2022-10-31 12:24 UTC, ivan-tms commented on Homework31.10/Homework31.10/Program.cs
> +        public string GetCourse()
Ты можешь сделать отдельное стринговое свойство только с гетером, которое возвращает отформатированную строку
Сетер в нём не делай

2022-11-01 13:10 UTC, closed without merging