Dmitry murauyou 02.11.2022
NET-18/Homework pull request #49
Opened 2022-11-01 16:45 UTC by DmitryMurauyou

2022-11-01 21:23 UTC, ivan-tms requested changes

2022-11-01 21:23 UTC, ivan-tms commented on HW_02.11.2022/HW_01.11.2022/Program.cs
> +            Console.WriteLine();
лучше без этого пустого вывода
если он тебе нужен, то выводи в вызывающем коде

2022-11-01 21:23 UTC, ivan-tms commented on HW_02.11.2022/HW_01.11.2022/Program.cs
> +        public string _name { get; set; }
свойства именуются не так

2022-11-01 21:24 UTC, ivan-tms commented
а как сюда попали Сашины коммиты?)

2022-11-02 11:12 UTC, DmitryMurauyou commented on HW_02.11.2022/HW_01.11.2022/Program.cs
> +        public string _name { get; set; }
По факту. С его компа пытались заливать домашку, вот и лишнее залилось)))

2022-11-02 11:50 UTC, ivan-tms commented on HW_02.11.2022/HW_01.11.2022/Program.cs
> +        public string _name { get; set; }
Исправь вещи, на которые я поставил комменты)

2022-11-11 06:39 UTC, closed without merging