andrew.Marchuk_Homework_02.11.2022
NET-18/Homework pull request #53
Opened 2022-11-02 12:31 UTC by AndrewM4k

2022-11-06 15:32 UTC, ivan-tms requested changes

2022-11-06 15:32 UTC, ivan-tms commented on Program.cs
> +        public virtual void Print(Person person)
перед методом нужна пустая строка

2022-11-06 15:32 UTC, ivan-tms commented on Program.cs
> +    public class Student : Person
и перед классом тоже

2022-11-06 15:32 UTC, ivan-tms commented on Program.cs
> +            else
если пишешь `if` с фигурными скобками, то и `else` пиши с ними тоже

2022-11-06 15:32 UTC, ivan-tms commented on Program.cs
> +
а вот тут пустая строка не нужна

2022-11-06 15:32 UTC, ivan-tms commented on Program.cs
> +            GC.Collect();
на данном этапе он не удалится, потому что на него есть ссылки
ты в теории можешь сделать это в методе `Main`, записав в изначальную ссылку (когда создавал объект) `null`

2022-11-06 15:32 UTC, ivan-tms commented on Program.cs
> +            Student NikitaStudent = new Student()
переменные внутри метода должны называться с маленькой буквы

2022-11-07 17:10 UTC, AndrewM4k commented on Program.cs
> +            GC.Collect();
ну то есть  конкретный студент = null, верно?

2022-11-08 20:39 UTC, ivan-tms commented on Program.cs
> +            GC.Collect();
да

2022-11-11 06:40 UTC, closed without merging