Kozyrev 02.11.2022
NET-18/Homework pull request #54
Opened 2022-11-03 20:47 UTC by KozyrevEvgeny

2022-11-03 20:54 UTC, KozyrevEvgeny commented
Там закоменченное в конце это попытка сделать до конца отчисленный и уволенный (нашел где-то в инете) с доп заданием не понял что именно нужно

2022-11-04 08:07 UTC, ivan-tms requested changes

2022-11-04 08:07 UTC, ivan-tms commented on kozyrev_02.11.2022/kozyrev_02.11.2022/Program.cs
> +            protected string name;
удаляй неиспользуемые члены класса
либо же используй их где-то =)

2022-11-04 08:07 UTC, ivan-tms commented on kozyrev_02.11.2022/kozyrev_02.11.2022/Program.cs
> +            public virtual void Print()
нужна пустая строка между свойствами и методом

2022-11-04 08:07 UTC, ivan-tms commented on kozyrev_02.11.2022/kozyrev_02.11.2022/Program.cs
> +
а вот тут пустая строка не нужна

2022-11-04 08:07 UTC, ivan-tms commented on kozyrev_02.11.2022/kozyrev_02.11.2022/Program.cs
> +        public class Student : Person
а вот здесь нужна =)

2022-11-04 08:07 UTC, ivan-tms commented on kozyrev_02.11.2022/kozyrev_02.11.2022/Program.cs
> +            private int numgroup;
удаляй неиспользуемые члены класса

2022-11-04 08:07 UTC, ivan-tms commented on kozyrev_02.11.2022/kozyrev_02.11.2022/Program.cs
> +            //private static void StatusStudent(Student student)
не коммить закомменченный код
это нехорошая практика

2022-11-11 06:40 UTC, closed without merging