Sergey Yushkevich 09.11.2022
NET-18/Homework pull request #55
Opened 2022-11-06 11:28 UTC by Sergey-Yushkevich

2022-11-06 15:20 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Bike.cs
> +            if (value is < 50 or > 350)
whaaaaaaaaaaaaaaaaat, так можно?)))
как начнёшь работать тоже будет не в курсе таких штук xDD

2022-11-06 15:28 UTC, ivan-tms requested changes

2022-11-06 15:28 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Car.cs
> +            if (value is < 0 or > 7)
чутка некорректное условие: меньше 4 точно не бывает (и 4-х ступенчатые остались только у Торетто), а вот у последней Camry 8 =)
или 0 это вариатор?)

2022-11-06 15:28 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Point.cs
> +    public double GetX() => this.x;
гетеры и сетеры как методы это для джавистов, натоящие альфа-дотнетчики пишут свойства))

2022-11-06 15:28 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Point.cs
> +        if (obj is not Point point)
ничоси, выглядит классно)

2022-11-06 15:28 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/StaticClass.cs
> +    public static double DistanceBetweenIMovable(IMovable first, IMovable second) =>
лучше назвать `Distance`
то что между `IMovable`'ами это видно по аргументам)

2022-11-06 15:28 UTC, ivan-tms commented on HomeWork_31.10.2022/HomeWork_31.10.2022.sln
> +﻿
чтобы не париться со всякими стэшами и всем такми просто удали эти файлы
из базовой ветки ты это не удалишь, но зато в этой не будет

2022-11-06 19:33 UTC, Sergey-Yushkevich commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Car.cs
> +            if (value is < 0 or > 7)
Не знаю, подумал про какие-нибудь детские, у которых одна))) а про 8 передач не знал

2022-11-06 19:35 UTC, Sergey-Yushkevich commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Point.cs
> +    public double GetX() => this.x;
Так а там есть смысл только в автосвойтсвах, а ты написал поля сделать в структуре(может перепутал)

2022-11-06 19:46 UTC, Sergey-Yushkevich commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Bike.cs
> +            if (value is < 50 or > 350)
райдер подсказал, думаю может потом запомню :)))

2022-11-08 20:12 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Bike.cs
> +            if (value is < 50 or > 350)
ну райдер такое любит)

2022-11-08 20:13 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Point.cs
> +    public double GetX() => this.x;
есть такая вероятность, что я проебался
но вроде старался проверить)

2022-11-08 20:14 UTC, ivan-tms requested changes

2022-11-08 20:14 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/Point.cs
> +    public double GetX() => this.x;
поменяй на свойство только с гетером

2022-11-22 20:47 UTC, ivan-tms requested changes
Класс назови осмысленно и будет топ)

2022-11-22 20:47 UTC, ivan-tms commented on HomeWork_09_11_2022/HomeWork_09_11_2022/StaticClass.cs
> +public static class StaticClass
Назови как-нибудь осмысленно)

2022-12-14 05:42 UTC, closed without merging