Andrew_Marchuk_09.11.2022
NET-18/Homework pull request #61
Opened 2022-11-08 19:37 UTC by AndrewM4k

2022-11-08 20:38 UTC, ivan-tms requested changes

2022-11-08 20:38 UTC, ivan-tms commented on Program.cs
> +            this.x = x; this.y = y;
лучше в одну строку ничего не записывать

2022-11-08 20:38 UTC, ivan-tms commented on Program.cs
> +        Point Points = new Point();
я бы сказал что это red flag на название поля, но оно тут абсолютно избыточно, по этому удали его, а свойство `Point` сделай автоматическим

2022-11-08 20:38 UTC, ivan-tms commented on Program.cs
> +        Point Points = new Point();
та же шарманка, то и для `Person`

2022-11-08 20:38 UTC, ivan-tms commented on Program.cs
> +        public static void Delta(IMovable Movable1, IMovable Movable2)
red flag: аргумент с большой буквы

2022-11-15 19:37 UTC, AndrewM4k commented on Program.cs
> +        Point Points = new Point();
не могу, ведь тогда я не смогу присвоить значение point.x ,без создания экземпляра

2022-11-15 19:37 UTC, AndrewM4k commented on Program.cs
> +        Point Points = new Point();
-//-

2022-11-15 19:39 UTC, AndrewM4k commented on Program.cs
> +        public static void Delta(IMovable Movable1, IMovable Movable2)
fixed

2022-11-15 19:39 UTC, AndrewM4k commented on Program.cs
> +            this.x = x; this.y = y;
Fixed

2022-11-20 13:06 UTC, AndrewM4k commented on Program.cs
> +        public static void Delta(IMovable Movable1, IMovable Movable2)
check commt, please

2022-11-22 20:39 UTC, ivan-tms commented on Program.cs
> +            this.x = x; this.y = y;
Не видно)

2022-11-22 20:40 UTC, ivan-tms requested changes

2022-11-22 20:40 UTC, ivan-tms commented on Program.cs
> +            Person Ivan = new Person();
И его переменных в методе должны быть в с маленькой буквы

2022-11-25 17:03 UTC, AndrewM4k commented on Program.cs
> +            Person Ivan = new Person();
не совсем понял, что не так?)

2022-11-25 17:08 UTC, AndrewM4k commented on Program.cs
> +            this.x = x; this.y = y;
fixed

2023-01-13 18:54 UTC, AndrewM4k commented
Check commit please

2023-01-13 19:36 UTC, AndrewM4k commented on Program.cs
> +            Person Ivan = new Person();
все ж с малой, вроде...

2023-01-15 22:28 UTC, closed without merging