Andrew_marchuk_16.11.2022_HomeworkType: easy
NET-18/Homework pull request #67
Opened 2022-11-15 20:57 UTC by AndrewM4k

2022-11-16 08:54 UTC, ivan-tms requested changes
Поменяй метод `Create`

2022-11-16 08:54 UTC, ivan-tms commented on Program.cs
> +            WeaponFactory.Create(p);
Лучше не передавать туда экземпляр класса, в который ты записываешь значение
Лучше сделай его просто возвращающим `T`, чтобы вызов выглядел примерно так
`var gun = WeaponFactory<Gun>()`

2022-11-20 14:26 UTC, AndrewM4k commented on Program.cs
> +            WeaponFactory.Create(p);
fixed

2022-11-20 14:28 UTC, AndrewM4k commented on Program.cs
> +            WeaponFactory.Create(p);
plus updades

2022-11-20 18:39 UTC, ivan-tms requested changes

2022-11-20 18:39 UTC, ivan-tms commented on WeaponFactory.cs
> +            if (result is PistolMakarov)
Вот такого вот делать не стоит
Я потом могу переиспользовать твой код и не получу должного результата со своим наследником класса `Weapon`
Добавь лучше аргумент в метод, чем хардкодить эти значения для конкретного типа

2022-11-20 18:39 UTC, ivan-tms commented on Weapon.cs
> +
Пустая строка

2022-11-20 18:39 UTC, ivan-tms commented on Weapon.cs
> +            for (; x > 0; x--)
Лучше вместо цикла просто отними одно от другого и это добавь к текущему количеству патронов
И верни разницу, раз уж считаешь такое😁

2022-11-20 18:39 UTC, ivan-tms commented on Objectfactory.cs
> +            var maxLoad = myType.GetProperty("MaxLoad");
Хардкодить плохо)
Но выглядит неплохо
Теперь попытайся проинициализировать все свойства объекта
Подсказка, нужно будет их перебрать циклом

2022-11-20 20:07 UTC, AndrewM4k commented on Weapon.cs
> +            for (; x > 0; x--)
fixed, no prblms

2022-11-20 20:07 UTC, AndrewM4k commented on Weapon.cs
> +
fixed

2022-11-20 20:08 UTC, AndrewM4k commented on Objectfactory.cs
> +            var maxLoad = myType.GetProperty("MaxLoad");
а что значит хардкодить? вроде сделал, но под разные характеристики логически просятся ограничения на диапазон рандома...

2022-11-21 11:54 UTC, ivan-tms requested changes

2022-11-21 11:54 UTC, ivan-tms commented on Objectfactory.cs
> +                int value4 = rnd.Next(0, 20);
А вдруг так будет не `int`?)

2022-11-21 11:54 UTC, ivan-tms commented on Objectfactory.cs
> +            //int value = rnd.Next(10, 20);
Не оставляй закомменченный код

2022-11-21 11:54 UTC, ivan-tms commented on Pistol.cs
> +            if (Load> MaxLoad)
Пробел

2022-11-25 17:16 UTC, AndrewM4k commented on Pistol.cs
> +            if (Load> MaxLoad)
fixed

2022-11-25 17:16 UTC, AndrewM4k commented on Objectfactory.cs
> +            //int value = rnd.Next(10, 20);
fixed

2022-11-25 17:16 UTC, AndrewM4k commented on WeaponFactory.cs
> +            if (result is PistolMakarov)
fixed

2022-12-14 05:55 UTC, closed without merging