arseni-ustinovich_24.10.2022
NET-18/Homework pull request #7
Opened 2022-10-25 10:25 UTC by Siion42

1,2 hw

2022-10-25 19:05 UTC, ivan-tms commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +            var flag = false;
флаги стоит называть более конкретно

2022-10-25 19:08 UTC, ivan-tms requested changes

2022-10-25 19:08 UTC, ivan-tms commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +            var flag = false;
флаги должны называться более конкретно (например isEvel, isOdd)

2022-10-25 19:08 UTC, ivan-tms commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +            while (flag);
удали, эта строчка не имеет смысла

2022-10-25 19:08 UTC, ivan-tms commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +                    callfuncs(numbers, el_num);
неплохо было бы вывести числа, которые были сгенерированы)

2022-10-25 19:28 UTC, Siion42 commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +                    callfuncs(numbers, el_num);
Console.WriteLine("{0, 4}) {1}", i+1,numbers[i]); 
они выводятся)))

2022-10-25 19:29 UTC, Siion42 commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +            while (flag);
?

2022-10-25 20:21 UTC, ivan-tms commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +            while (flag);
на которую я оставил коммент =)
с циклом while

2022-10-25 20:21 UTC, ivan-tms commented on arseni-ustinovich_24.10.2022/HW_1/Program.cs
> +                    callfuncs(numbers, el_num);
упс, я слепой

2022-10-26 21:41 UTC, Siion42 commented
Исправил!

2022-10-29 06:26 UTC, closed without merging