Arseni ustinovich 28.11.2022
NET-18/Homework pull request #80
Opened 2022-11-27 14:10 UTC by Siion42

Сделать асинхронный метод, который с промежутком в полсекунды 10 раз что-то выведет на консоль. В мейне вызвать его и не await’ить (!). Дальше в мейне вызовите асинхронную задержку на 2 секунды. После этого вызовите задержку потока на 2 секунды. Запустите, проанализируйте результаты и попытайтесь понять почему что и как
    Получите какой-нибудь текст с консоли и асинхронно запишите его в файл. После этого асинхронно прочитайте текст из этого файла и выведите его а консоль.
    
    работает очень интересно конечно

2022-12-04 14:36 UTC, ivan-tms requested changes
Всё круто, поправь пару момэнтов и апрувну

2022-12-04 14:36 UTC, ivan-tms commented on arseni-ustinovich_28.11.2022/HW_12/Program.cs
> +
Ни ни

2022-12-04 14:36 UTC, ivan-tms commented on arseni-ustinovich_28.11.2022/HW_12/Program.cs
> +            string text = await File.ReadAllTextAsync(filePath);
Просто напиши `return await ...`

2022-12-04 14:36 UTC, ivan-tms commented on arseni-ustinovich_28.11.2022/HW_12/Program.cs
> +
Ни ни

2022-12-07 03:52 UTC, Siion42 commented on arseni-ustinovich_28.11.2022/HW_12/Program.cs
> +
?

2022-12-07 03:54 UTC, Siion42 commented on arseni-ustinovich_28.11.2022/HW_12/Program.cs
> +
Ты серьезно на пустую строку оставил комм?))))

2022-12-13 20:11 UTC, closed without merging