Andrew_Marchuk_Homework_14.12.2022
NET-18/Homework pull request #84
Opened 2022-12-11 16:49 UTC by AndrewM4k

2022-12-13 20:04 UTC, ivan-tms requested changes

2022-12-13 20:04 UTC, ivan-tms commented on Hard_Type/Program.cs
> +            WebClient client = new WebClient();
Лучше юзай `HttpClient`

2022-12-13 20:04 UTC, ivan-tms commented on Hard_Type/Program.cs
> +
Простыню убери

2022-12-13 20:04 UTC, ivan-tms commented on Hard_Type/Program.cs
> +            string filePath = "RandomSites.txt";
Писать всё в один файл опасно
Лучше либо заюзать разные файлы либо как-то потоки синхронизировать, но получится не параллельное выполнение

2022-12-13 20:04 UTC, ivan-tms commented on Hard_Type/Program.cs
> +            Task.WhenAll(tasks).Wait();
Выше ты юзаешь асинхронность, а чего здесь не юзаешь?)
Или ты решил проверить на себе какого было людям до C# версии 7.1?)

2022-12-13 20:04 UTC, ivan-tms commented on Easy_Type/Program.cs
> +            //Console.WriteLine("StringRandom Start");
Убери если не нужна

2022-12-13 20:04 UTC, ivan-tms commented on Easy_Type/SimpleTask.cs
> +    internal class SimpleTask
Удали его если он тебе не нужен

2022-12-13 20:04 UTC, ivan-tms commented on Easy_Type/Class1.cs
> +    internal class Pub
Удали если он тебе не нужен

2022-12-18 12:21 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +            WebClient client = new WebClient();
fixed

2022-12-18 12:21 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +
fixed

2022-12-18 12:21 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +            string filePath = "RandomSites.txt";
fixed

2022-12-18 12:21 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +            Task.WhenAll(tasks).Wait();
fixed

2022-12-18 12:22 UTC, AndrewM4k commented on Easy_Type/Program.cs
> +            //Console.WriteLine("StringRandom Start");
fixed

2022-12-18 12:23 UTC, AndrewM4k commented on Easy_Type/SimpleTask.cs
> +    internal class SimpleTask
fixed

2022-12-18 12:24 UTC, AndrewM4k commented on Easy_Type/Class1.cs
> +    internal class Pub
fixed

2022-12-25 17:00 UTC, ivan-tms requested changes

2022-12-25 17:00 UTC, ivan-tms commented on Easy_Type/Program.cs
> +            var t = DateTime.Now;
Не обзывай переменные одной буквой
По названию не будет понятно что они делают
Исключение конечно переменные цикла

2022-12-25 17:00 UTC, ivan-tms commented on Easy_Type/Program.cs
> +                tasks.Add(Task.Run(() => StringRandom(v, j++)));
Не надо делать `Task.Run`, чтобы добавить эту задачу в список
Достаточно просто вызывать этот метод без слова `await`

2022-12-25 17:00 UTC, ivan-tms commented on Hard_Type/Program.cs
> +
А здесь чего не убрал?

2022-12-26 16:05 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +
Because I am Dolbayob, fixed

2022-12-26 16:05 UTC, AndrewM4k commented on Easy_Type/Program.cs
> +                tasks.Add(Task.Run(() => StringRandom(v, j++)));
fixed

2022-12-26 16:05 UTC, AndrewM4k commented on Easy_Type/Program.cs
> +            var t = DateTime.Now;
fixed

2022-12-26 20:31 UTC, ivan-tms requested changes

2022-12-26 20:31 UTC, ivan-tms commented on Easy_Type/Program.cs
> +            var time = DateTime.Now;
Раз уж не поменял все эти однобуквенные имена, то доебусь до `time`
Это слишком абстрактное название
Ты ведь сохраняешь время начала выполнения, а не просто абстрактное время
Вот и думай над названиями)

2022-12-26 20:31 UTC, ivan-tms commented on Easy_Type/Program.cs
> +            int j = 0;
Её объяви в цикле

2022-12-26 20:31 UTC, ivan-tms commented on Easy_Type/Program.cs
> +            int v = 1000;
Обзови нормально

2022-12-26 20:31 UTC, ivan-tms commented on Hard_Type/Program.cs
> +            int j = 1;
Прижми её к `foreach`, будет понятнее что на к нему относится

2022-12-26 20:31 UTC, ivan-tms commented on Hard_Type/Program.cs
> +        public static async Task<string> DownloadWebsite(string websiteURL, int j)
Шо за `j`

2022-12-26 20:31 UTC, ivan-tms commented on Hard_Type/Program.cs
> +            Task.WhenAll(tasks).Wait();
Что fixed, если ты ниже юзаешь `.Wait`?)

2022-12-26 20:31 UTC, ivan-tms commented on Hard_Type/Program.cs
> +            int j = 0;
Что за `j`?

2023-01-13 19:24 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +            Task.WhenAll(tasks).Wait();
Fixed! blyat!

2023-01-13 19:26 UTC, AndrewM4k commented on Easy_Type/Program.cs
> +            var time = DateTime.Now;
фиксед

2023-01-13 19:30 UTC, AndrewM4k commented on Easy_Type/Program.cs
> +            int j = 0;
как?)

2023-01-13 19:30 UTC, AndrewM4k commented on Easy_Type/Program.cs
> +            int v = 1000;
fixed

2023-01-13 19:31 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +            int j = 1;
fixed

2023-01-13 19:32 UTC, AndrewM4k commented on Hard_Type/Program.cs
> +        public static async Task<string> DownloadWebsite(string websiteURL, int j)
fixed

2023-01-13 19:33 UTC, AndrewM4k commented
fixed, check,pls

2023-01-15 22:28 UTC, closed without merging