Bobko 26.10.2022
NET-18/Homework pull request #9
Opened 2022-10-25 13:26 UTC by lamer27

2022-10-25 18:16 UTC, ivan-tms requested changes

2022-10-25 18:16 UTC, ivan-tms commented on HomeWork_3/homework3.txt
> +namespace PersonApp1
а теперь возьми этот код, вставь в нормальный проект и запуш ещё раз)

2022-10-26 05:56 UTC, ivan-tms requested changes

2022-10-26 05:56 UTC, ivan-tms commented on HomeWork_3/PersonApp1/Program.cs
> +        public string _Name;
поля именуются с маленькой буквы

2022-10-26 05:56 UTC, ivan-tms commented on HomeWork_3/PersonApp1/Program.cs
> +
добавь конструктор с параметрами (имя, фамилия, возраст) и конструктор без параметров

2022-10-26 05:56 UTC, ivan-tms commented on HomeWork_3/PersonApp1/Program.cs
> +            Console.Write($"Вы {t._SurName}");
надо сформировать строку для вывода и вывести одним `WriteLine`'ом

2022-10-26 05:56 UTC, ivan-tms commented on HomeWork_4/DistanceApp/Program.cs
> +    internal struct Program
нельзя трогать класс `Program`, он должен остаться таким, каким его сгенерировала студия
сделай отдельный структуру с названием типа `Coordinates` с тремя координатами и проводи операции уже над ним

2022-10-26 08:38 UTC, lamer27 commented on HomeWork_3/PersonApp1/Program.cs
> +
я не понимаю
вроде бы это и есть конструктор без параметров (на скрине), а параметры в Main задаются или я неправильно понял?

2022-10-29 06:25 UTC, ivan-tms requested changes

2022-10-29 06:25 UTC, ivan-tms commented on HomeWork_3/PersonApp1/Program.cs
> +
нужны два конструктора, которые ты объявляешь руками: без параметров, который бы записал в поля какие-то дефолтные значения и с параметрами, который записывает в поля переданные ему параметры

2022-10-29 06:25 UTC, ivan-tms commented on HomeWork_4/DistanceApp/Program.cs
> +        struct Solid
эта структура должна хранить один набор координат, то есть поля x, y, z
когда ты будешь рассчитывать расстояние между точками, тебе надо будет передать два экземпляра этой структуры в метод

2022-10-30 08:25 UTC, ivan-tms commented
сейчас выглядит хорошо
сделай дз на 31.10, если ещё не делал)

2022-10-30 08:25 UTC, closed without merging